name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env: 
      CI: true
<<<<<<< HEAD
      MONGO_URL: mongodb://localhost/nasa
    Strategy: 
=======
    strategy: 
>>>>>>> 158708a13f85567b4d1785bd6862619d5e215652
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js Version ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: '${{matrix.node-version}}'
      - name: Use MongoDB from github actions
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '${{matrix.mongodb-version}}'
      - run: npm run install-all
      - run: npm run build --prefix client
      - run: npm test
